// ============================================================
// 대학별 입장 코드 설정
// 코드를 바꾸고 싶으면 여기서 수정 후 터미널에서 실행:
//   node supabase/university-codes.js
// → seed-universities.sql 파일이 자동으로 업데이트됩니다.
// ============================================================

// ⚠️ 테스트용: 모든 학교 코드를 001로 통일. 실제 배포 전에 각각 다른 코드로 변경할 것!
const UNIVERSITIES = [
  { name: '가천대학교(글로벌)',       code: '001' },
  { name: '가톨릭대학교(성심)',       code: '001' },
  { name: '강남대학교',              code: '001' },
  { name: '경기대학교',              code: '001' },
  { name: '경북대학교',              code: '001' },
  { name: '경상국립대학교',           code: '001' },
  { name: '경성대학교',              code: '001' },
  { name: '경희대학교(국제/서울)',    code: '001' },
  { name: '계명대학교',              code: '001' },
  { name: '고려대학교(서울)',         code: '001' },
  { name: '고려대학교(세종)',         code: '001' },
  { name: '공주대학교(천안)',         code: '001' },
  { name: '광운대학교',              code: '001' },
  { name: '국립금오공과대학교',        code: '001' },
  { name: '국립순천대학교',           code: '001' },
  { name: '국립창원대학교',           code: '001' },
  { name: '국민대학교',              code: '001' },
  { name: '단국대학교(죽전)',         code: '001' },
  { name: '대구대학교',              code: '001' },
  { name: '덕성여자대학교',           code: '001' },
  { name: '동국대학교',              code: '001' },
  { name: '동덕여자대학교',           code: '001' },
  { name: '동아대학교',              code: '001' },
  { name: '명지대학교(인문)',         code: '001' },
  { name: '명지대학교(자연)',         code: '001' },
  { name: '백석대학교',              code: '001' },
  { name: '삼육대학교',              code: '001' },
  { name: '상명대학교(서울)',         code: '001' },
  { name: '상명대학교(천안)',         code: '001' },
  { name: '서강대학교',              code: '001' },
  { name: '서경대학교',              code: '001' },
  { name: '서울과학기술대학교',        code: '001' },
  { name: '서울대학교',              code: '001' },
  { name: '서울여자대학교',           code: '001' },
  { name: '서울예술대학교',           code: '001' },
  { name: '서일대학교',              code: '001' },
  { name: '선문대학교',              code: '001' },
  { name: '성결대학교',              code: '001' },
  { name: '성공회대학교',             code: '001' },
  { name: '성균관대학교(인문/자연)',   code: '001' },
  { name: '성신여자대학교',           code: '001' },
  { name: '세종대학교',              code: '001' },
  { name: '수원대학교',              code: '001' },
  { name: '숙명여자대학교',           code: '001' },
  { name: '순천향대학교',             code: '001' },
  { name: '숭실대학교',              code: '001' },
  { name: '신한대학교',              code: '001' },
  { name: '연세대학교(미래)',         code: '001' },
  { name: '연세대학교(서울)',         code: '001' },
  { name: '연암공과대학교',           code: '001' },
  { name: '영남대학교',              code: '001' },
  { name: '을지대학교(성남)',         code: '001' },
  { name: '이화여자대학교',           code: '001' },
  { name: '인천대학교',              code: '001' },
  { name: '인하대학교',              code: '001' },
  { name: '전북대학교',              code: '001' },
  { name: '제주대학교',              code: '001' },
  { name: '중부대학교(고양)',         code: '001' },
  { name: '중앙대학교',              code: '001' },
  { name: '차의과학대학교',           code: '001' },
  { name: '청주대학교',              code: '001' },
  { name: '충남대학교',              code: '001' },
  { name: '충북대학교',              code: '001' },
  { name: '태재대학교',              code: '001' },
  { name: '평택대학교',              code: '001' },
  { name: '한국공학대학교',           code: '001' },
  { name: '한국교통대학교(충주)',      code: '001' },
  { name: '한국기술교육대학교',        code: '001' },
  { name: '한국외국어대학교(글로벌)',  code: '001' },
  { name: '한국외국어대학교(서울)',    code: '001' },
  { name: '한국항공대학교',           code: '001' },
  { name: '한남대학교',              code: '001' },
  { name: '한동대학교',              code: '001' },
  { name: '한림대학교',              code: '001' },
  { name: '한밭대학교',              code: '001' },
  { name: '한서대학교(서산)',         code: '001' },
  { name: '한성대학교',              code: '001' },
  { name: '한양대학교(ERICA)',        code: '001' },
  { name: '호서대학교(아산/천안)',     code: '001' },
  { name: '홍익대학교(서울)',         code: '001' },
];

// --- 아래는 수정하지 마세요 ---
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const rows = UNIVERSITIES.map(({ name, code }, i) => {
  const hash = crypto.createHash('sha256').update(code).digest('hex');
  const comma = i < UNIVERSITIES.length - 1 ? ',' : '';
  return `  ('${name.replace(/'/g, "''")}', '${hash}')${comma}  -- ${code}`;
});

const sql = `-- AUTO-GENERATED by university-codes.js — 직접 수정하지 마세요
-- 코드를 바꾸려면 university-codes.js 에서 수정 후 node로 실행하세요

INSERT INTO universities (name, open_code_hash) VALUES
${rows.join(',\n')}
ON CONFLICT (name) DO UPDATE SET open_code_hash = EXCLUDED.open_code_hash;
`;

const outPath = path.join(__dirname, 'seed-universities.sql');
fs.writeFileSync(outPath, sql, 'utf8');
console.log(`✅ seed-universities.sql 업데이트 완료 (${UNIVERSITIES.length}개 대학)`);
UNIVERSITIES.forEach(({ name, code }) => console.log(`  ${code}  ${name}`));
